# COLOR
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_YELLOW = (255, 255, 0)
COLOR_BLUE = (0, 0, 255)

# PLAYER
PLAYER_ONE_ID = 1
PLAYER_ONE_NAME = 'Player 1'
PLAYER_TWO_ID = 2
PLAYER_TWO_NAME = 'Player 2'

# MENU
MENU_BACKGROUND = ''
MENU_OPTIONS = ('JOGAR', 'COMANDOS', 'AJUSTES', 'SCORES', 'SAIR')
MENU_TITLE = 'MENU PRINCIPAL'
MENU_COMMANDS_TITLE = 'COMANDOS'
MENU_COMMANDS_GAME = ('JOGO:', 'Space - Pular')
MENU_COMMANDS = ('MENU:', 'Seta para Cima ↑ - Subir', 'Seta para baico ↓ - Descer', 'Enter - Selecionar')
MENU_COMMANDS_RETURN = ('Prescione ENTER para continuar.')

# WINDOW
WINDOW_MENU_WIDTH = 580
WINDOW_MENU_HEIGHT = 480