# COLOR
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_YELLOW = (255, 255, 0)
COLOR_BLUE = (0, 0, 255)

#BACKGROUND
BACKGROUND_SPEED = 0.3
BACKGROUND_FOLDER_NAME = 'game_background'

# PLAYER
PLAYER_SPEED = 1.2
PLAYER_WIDTH = 160
PLAYER_HEIGHT = 110
PLAYER_SCORE = 0

# MENU
MENU_BACKGROUND = ''
MENU_OPTIONS = ('JOGAR', 'COMANDOS', 'AJUSTES', 'SCORES', 'SAIR')
MENU_TITLE = 'MENU PRINCIPAL'

# COMMANDS
COMMANDS_TITLE = 'MENU DE COMANDOS'
COMMANDS_GAME = ('JOGO:', 'Space - Pular')
COMMANDS = ('MENU:', 'Seta para Cima ↑ - Subir', 'Seta para baico ↓ - Descer', 'Enter - Selecionar')
COMMANDS_RETURN = 'Pressione ENTER para continuar.'

# SETTINGS
SETTINGS_TITLE = 'MENU DE AJUSTES'
SETTINGS_SHOW_FPS = 'MOSTRAR FPS'
SETTINGS_HIDDEN_FPS = 'ESCONDER FPS'
SETTINGS_RETURN = 'VOLTAR'

# WINDOW
WINDOW_GAME_WIDTH = 640
WINDOW_GAME_HEIGHT = 450
WINDOW_MENU_WIDTH = 640
WINDOW_MENU_HEIGHT = 450